modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-mushroomfieldsdimension"
license = "ARR"

[[mods]]
modId = "mushroomfieldsdimension"
version = "${version}"
displayName = "Mushroom Fields Dimension"
authors = "mahmudindev"
description = '''
Add mushroom fields single biome world type as separate dimension.
'''
logoFile = "assets/mushroomfieldsdimension/icon.png"

[[dependencies.mushroomfieldsdimension]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mushroomfieldsdimension]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mushroomfieldsdimension]]
modId = "dimensionfixer"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.mushroomfieldsdimension]]
modId = "worldportal"
mandatory = true
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"
