modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/mahmudindev/mcmod-mushroomfieldsdimension"
license = "ARR"

[[mods]]
modId = "mushroomfieldsdimension"
version = "${version}"
displayName = "Mushroom Fields Dimension"
authors = "mahmudindev"
description = '''
Add mushroom fields single biome world type as separate dimension.
'''
logoFile = "assets/mushroomfieldsdimension/icon.png"

[[dependencies.mushroomfieldsdimension]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mushroomfieldsdimension]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.mushroomfieldsdimension]]
modId = "dimensionfixer"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[dependencies.mushroomfieldsdimension]]
modId = "worldportal"
type = "required"
versionRange = "[0.0.9,)"
ordering = "NONE"
side = "SERVER"

[[mixins]]
config = "mushroomfieldsdimension.mixins.json"
